INSERT INTO rating_category (category, standard_percentage) VALUES ('A', 10);
INSERT INTO rating_category (category, standard_percentage) VALUES ('B', 20);
INSERT INTO rating_category (category, standard_percentage) VALUES ('C', 40);
INSERT INTO rating_category (category, standard_percentage) VALUES ('D', 20);
INSERT INTO rating_category (category, standard_percentage) VALUES ('E', 10);

INSERT INTO employee (name, rating) VALUES ('Harry 1', 'A');
INSERT INTO employee (name, rating) VALUES ('Harry 3', 'B');
INSERT INTO employee (name, rating) VALUES ('Harry 4', 'C');
INSERT INTO employee (name, rating) VALUES ('Harry 2', 'D');
INSERT INTO employee (name, rating) VALUES ('Harry 5', 'E');
INSERT INTO employee (name, rating) VALUES ('Harry 7', 'A');
INSERT INTO employee (name, rating) VALUES ('Harry 6', 'C');
INSERT INTO employee (name, rating) VALUES ('Harry 8', 'D');
INSERT INTO employee (name, rating) VALUES ('Harry 9', 'B');
INSERT INTO employee (name, rating) VALUES ('Harry 10', 'E');
INSERT INTO employee (name, rating) VALUES ('Harry 13', 'A');
INSERT INTO employee (name, rating) VALUES ('Harry 12', 'C');
INSERT INTO employee (name, rating) VALUES ('Harry 14', 'D');
INSERT INTO employee (name, rating) VALUES ('Harry 15', 'C');
INSERT INTO employee (name, rating) VALUES ('Harry 11', 'E');